# Generated by Django 5.0 on 2023-12-11 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['oid'], 'verbose_name': 'Catalogo', 'verbose_name_plural': 'Catalogos'},
        ),
        migrations.AlterField(
            model_name='producto',
            name='create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='fecha de creacion'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='description',
            field=models.TextField(verbose_name='descripcion'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='image',
            field=models.ImageField(upload_to='catalogos', verbose_name='imagen'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='title',
            field=models.CharField(max_length=20, verbose_name='titulo'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='update',
            field=models.DateTimeField(auto_now=True, verbose_name='fecha de modificacion'),
        ),
    ]
